# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 458fb97e5c7dda61b41c77453e9c2c40dc7127b63ec21efab1ff5fae3eb8bae9f52cbd17964904c444eb76236c8584cdf4f7255b478c32467cb93e1a69e1d3ad

test:
  secret_key_base: fbf839afbbf17847d33eed43cdcf660207ec4f25e71c9ac71a863a3b60a9d101f2dd12ecc8233721f912e5b08f4ddd1f04c1f916728e70be2ded3a76bf1814ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  payjp_secret_key: <%= ENV["PAYJP_SECRET_KEY"] %>
